export const SEARCH_FOR_PROGRESSION_MODAL_REQUEST =
  'SEARCH_FOR_PROGRESSION_MODAL_REQUEST';
export const SEARCH_FOR_PROGRESSION_MODAL_SUCCESS =
  'SEARCH_FOR_PROGRESSION_MODAL_SUCCESS';
export const SEARCH_FOR_PROGRESSION_MODAL_FAILURE =
  'SEARCH_FOR_PROGRESSION_MODAL_FAILURE';
export const SEARCH_FOR_INDUSTRY_TYPE_CODE_FAILURE =
  'SEARCH_FOR_INDUSTRY_TYPE_CODE_FAILURE';
export const SEARCH_FOR_INDUSTRY_TYPE_CODE_SUCCESS =
  'SEARCH_FOR_INDUSTRY_TYPE_CODE_SUCCESS';
export const SEARCH_FOR_INDUSTRY_TYPE_CODE_REQUEST =
  'SEARCH_FOR_INDUSTRY_TYPE_CODE_REQUEST';

export const SEARCH_FOR_OCCUPATION_TYPE_CODE_FAILURE =
  'SEARCH_FOR_OCCUPATION_TYPE_CODE_FAILURE';
export const SEARCH_FOR_OCCUPATION_TYPE_CODE_SUCCESS =
  'SEARCH_FOR_OCCUPATION_TYPE_CODE_SUCCESS';
export const SEARCH_FOR_OCCUPATION_TYPE_CODE_REQUEST =
  'SEARCH_FOR_OCCUPATION_TYPE_CODE_REQUEST';
