export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE';

export const GET_DATA_FOR_PATHWAY_AND_COMPONENTS_REQUEST =
  'GET_DATA_FOR_PATHWAY_AND_COMPONENTS_REQUEST';
export const GET_DATA_FOR_PATHWAY_AND_COMPONENTS_SUCCESS =
  'GET_DATA_FOR_PATHWAY_AND_COMPONENTS_SUCCESS';
export const GET_DATA_FOR_PATHWAY_AND_COMPONENTS_FAILURE =
  'GET_DATA_FOR_PATHWAY_AND_COMPONENTS_FAILURE';

export const SAVE_PATHWAY_DATA_REQUEST = 'SAVE_PATHWAY_DATA_REQUEST';
export const SAVE_PATHWAY_DATA_SUCCESS = 'SAVE_PATHWAY_DATA_SUCCESS';
export const SAVE_PATHWAY_DATA_FAILURE = 'SAVE_PATHWAY_DATA_FAILURE';

export const APPROVE_PATHWAY_REQUEST = 'APPROVE_PATHWAY_REQUEST';
export const APPROVE_PATHWAY_SUCCESS = 'APPROVE_PATHWAY_SUCCESS';
export const APPROVE_PATHWAY_FAILURE = 'APPROVE_PATHWAY_FAILURE';
export const SEARCH_INDUSTRY_TYPE_REQUEST = 'SEARCH_INDUSTRY_TYPE_REQUEST';
export const SEARCH_INDUSTRY_TYPE_SUCCESS = 'SEARCH_INDUSTRY_TYPE_SUCCESS';
export const SEARCH_INDUSTRY_TYPE_FAILURE = 'SEARCH_INDUSTRY_TYPE_FAILURE';

export const SEARCH_OCCUPATION_TYPE_REQUEST = 'SEARCH_OCCUPATION_TYPE_REQUEST';
export const SEARCH_OCCUPATION_TYPE_SUCCESS = 'SEARCH_OCCUPATION_TYPE_SUCCESS';
export const SEARCH_OCCUPATION_TYPE_FAILURE = 'SEARCH_OCCUPATION_TYPE_FAILURE';
