export const GET_ALL_PROXY_FOR_RESCOURCES_REQUEST =
  'GET_ALL_PROXY_FOR_RESCOURCES_REQUEST';
export const GET_ALL_PROXY_FOR_RESCOURCES_SUCCESS =
  'GET_ALL_PROXY_FOR_RESCOURCES_SUCCESS';
export const GET_ALL_PROXY_FOR_RESCOURCES_FAILURE =
  'GET_ALL_PROXY_FOR_RESCOURCES_FAILURE';
export const GET_ALL_ORGANIZATIONS_REQUEST = 'GET_ALL_ORGANIZATIONS_REQUEST';
export const GET_ALL_ORGANIZATIONS_SUCCESS = 'GET_ALL_ORGANIZATIONS_SUCCESS';
export const GET_ALL_ORGANIZATIONS_FAILURE = 'GET_ALL_ORGANIZATIONS_FAILURE';
