export const GET_LEFT_PANEL_PATHWAY_COMPONENTS_REQUEST =
  'GET_LEFT_PANEL_PATHWAY_COMPONENTS_REQUEST';
export const GET_LEFT_PANEL_PATHWAY_COMPONENTS_SUCCESS =
  'GET_LEFT_PANEL_PATHWAY_COMPONENTS_SUCCESS';
export const GET_LEFT_PANEL_PATHWAY_COMPONENTS_FAILURE =
  'GET_LEFT_PANEL_PATHWAY_COMPONENTS_FAILURE';
