export const GET_LEFT_PANEL_PATHWAY_COMPONENTS_REQUEST =
  'GET_LEFT_PANEL_PATHWAY_COMPONENTS_REQUEST';
export const GET_LEFT_PANEL_PATHWAY_COMPONENTS_SUCCESS =
  'GET_LEFT_PANEL_PATHWAY_COMPONENTS_SUCCESS';
export const GET_LEFT_PANEL_PATHWAY_COMPONENTS_FAILURE =
  'GET_LEFT_PANEL_PATHWAY_COMPONENTS_FAILURE';
export const ADD_COMPONENT_TO_LEFT_PANEL = 'ADD_COMPONENT_TO_LEFT_PANEL';
