export const GET_LOGICAL_OPERATOR_REQUEST = 'GET_LOGICAL_OPERATOR_REQUEST';
export const GET_LOGICAL_OPERATOR_SUCCESS = 'GET_LOGICAL_OPERATOR_SUCCESS';
export const GET_LOGICAL_OPERATOR_FAILURE = 'GET_LOGICAL_OPERATOR_FAILURE';

export const GET_ALL_COMPARATORS_REQUEST = 'GET_ALL_COMPARATORS_REQUEST';
export const GET_ALL_COMPARATORS_SUCCESS = 'GET_ALL_COMPARATORS_SUCCESS';
export const GET_ALL_COMPARATORS_FAILURE = 'GET_ALL_COMPARATORS_FAILURE';

export const GET_ARRAY_CONCEPT_REQUEST = 'GET_ARRAY_CONCEPT_REQUEST';
export const GET_ARRAY_CONCEPT_SUCCESS = 'GET_ARRAY_CONCEPT_SUCCESS';
export const GET_ARRAY_CONCEPT_FAILURE = 'GET_ARRAY_CONCEPT_FAILURE';

export const GET_CONSTRAINT_OPERAND_REQUEST = 'GET_CONSTRAINT_OPERAND_REQUEST';
export const GET_CONSTRAINT_OPERAND_SUCCESS = 'GET_CONSTRAINT_OPERAND_SUCCESS';
export const GET_CONSTRAINT_OPERAND_FAILURE = 'GET_CONSTRAINT_OPERAND_FAILURE';
